global:
  scrape_interval:     1s

  external_labels:
    monitor: 'elli-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'erlsrv'
    static_configs:
      - targets: ['127.0.0.1:3000']
